### 03 numpy.array 基础

In [2]:
import numpy as np

#### Python List的特点

每一个元素可以是任意类型,因此效率较低

无矩阵运算相关的函数

In [5]:
lst = [i for i in range(10)]
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
lst[2] = 100
lst

[0, 1, 100, 3, 4, 5, 6, 7, 8, 9]

In [11]:
lst[2] = 'Test'  # 元素类型改为字符串
lst

[0, 1, 'Test', 3, 4, 5, 6, 7, 8, 9]

In [16]:
import array

arr = array.array('i',[i for i in range(10)])  # 'i'表示元素类型为整型
arr

# 无法将元素修改为字符串
arr[2] = 'Test'  # 报错了

TypeError: an integer is required (got type str)

In [19]:
# 如果修改为浮点数,会报错
arr[1] = 1.0

# array的缺点是没有将数据当做向量或者矩阵，不支持基本运算。

TypeError: integer argument expected, got float

In [21]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# 无法将元素修改为字符串
nparr[2] = 'Test'  # 报错了


ValueError: invalid literal for int() with base 10: 'Test'

In [29]:
# 如果修改为浮点数,会隐式转换为Int类型,丢失精度
nparr[2] = 4.33
print(nparr)  # 发现第三个元素是整数4
print('nparr数据类型为:',nparr.dtype)

[0 1 4 3 4 5 6 7 8 9]
nparr数据类型为: int32


In [31]:
# 如果一开始np的array定义为float,会怎样?
nparr2 = np.array([1,2,3,4,5.44,6.44,7.66])
print(nparr2)
print('nparr2数据类型为:',nparr2.dtype)



[1.   2.   3.   4.   5.44 6.44 7.66]
nparr2数据类型为: float64
