### 05 numpy.array 基本操作

In [40]:
import numpy as np

In [41]:
# 创建一个一维数组
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# 创建一个二维数组
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### numpy.array 的基本属性

In [43]:
# .ndim 返回数组维度
x.ndim  

1

In [44]:
X.ndim

2

In [45]:
# .shape 数据形状
x.shape

(10,)

In [46]:
X.shape

(3, 5)

In [47]:
# .size 数组大小
x.size

10

In [48]:
X.size

15

In [49]:
#### numpy.array 的数据访问

In [50]:
# 索引
x[1]  # 下标为1的元素

1

In [51]:
X[1]  # 行下标为1的数据

array([5, 6, 7, 8, 9])

In [52]:
X[1,3]  # 行下标为1,列下标为3的元素

8

In [53]:
# 切片
x[:2]  # 前2个元素

array([0, 1])

In [54]:
x[1:3]  # 下标为[1,3)的数据,左开右闭,与Python切片操作一致

array([1, 2])

In [55]:
x[1::2]  # 从下标为的数字开始,步长为2

array([1, 3, 5, 7, 9])

In [59]:
x[::-1]  # 倒着返回数据

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [60]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
X[:2]  # 前2行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
X[:, :2]  # 前2列

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [62]:
X[:2, :3]  # 前2行,前3列数据

array([[0, 1, 2],
       [5, 6, 7]])

In [65]:
X[:2][:3]  # 结果不一样,是先取前2行数据,然后再该数据基础上再取前3行在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
X[:2, ::2]  # 前2行,列数按步长为2取数据,可以类比一维数据同样的切片操作


array([[0, 2, 4],
       [5, 7, 9]])

In [68]:
X[::-1, ::-1]  # 行列全部倒着取数

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [70]:
X[0, :]  # 下标为0的行 + 所有列


array([0, 1, 2, 3, 4])

In [73]:
X[:, 0]  # 所有行 + 下标为0的列

array([ 0,  5, 10])

#### Subarray of numpy.array

In [76]:
subX = X[:2, :3]  # 取前2列,前3行数据,赋值给subX
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [79]:
subX[0,0] = 1010
subX  # 子数组发生变化,那原数组X呢?

array([[1010,    1,    2],
       [   5,    6,    7]])

In [83]:
X  # 发现原数组也发生了变化,和Python list同类操作不一样,需要注意
# 因为Numpy比较注重性能,所以上述赋值操作,并不是像Python一样,新创建了一个数组赋给subX,而是直接将引用赋值给了subX
X[0,0] = 0  # 恢复原来的数据

In [85]:
# 如果不想赋值引用,只是简单的复制数组,那么调用.copy()即可
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [87]:
subX[0, 0] = 1010
subX  # 数据发生变化

array([[1010,    1,    2],
       [   5,    6,    7]])

In [90]:
X  # 未发生任何变化

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### reshape() 操作