### Numpy中的比较和Fancy Indexing

#### Fancy Indexing

In [15]:
import numpy as np

##### 原数据-----一维数组 

In [16]:
x = np.arange(1,17)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
# 一维数组索引
ind = [3, 5, 8]
x[ind]  #  等价于[x[3], x[5], x[8]]

array([4, 6, 9])

In [18]:
# 二维数组索引
ind = np.array([[0, 1, 3],
                [1, 2, 3]])
x[ind]  # 依次取下标对应的值组成新的数组

array([[1, 2, 4],
       [2, 3, 4]])

##### 原数据----二维数组 

In [24]:
X = x.reshape(4, 4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
row = [0, 2, 3]  # 行索引
col = [1, 2, 3]  # 列索引
X[row, col]  # X下标对应(0,1) (2,2) (3,3)的值组成的列表

array([ 2, 11, 16])

In [33]:
# 如果行或列为bool型索引呢?
row = [True, False, True, False]  # 第1,3行取值,2,4行不参与
X[row,0:2]  # 1,3行的前两列值

array([[ 1,  2],
       [ 9, 10]])

#### numpy.array的比较

In [35]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [37]:
x < 3  # 每个元素都和3比较,返回bool数组

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [39]:
x * 2 == 12 - x * 2  # 允许数学计算

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
X > 6  # 返回bool矩阵

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### 使用 numpy.array 的比较结果

In [46]:
np.sum(x < 5)  # x数组中小于5的数求和

4

In [58]:
np.count_nonzero(x)  # 统计非0元素个数

16

In [66]:
np.any(x == 1)  # 只要有一个True,返回True;全为False时,返回False

True

In [68]:
np.all(x == 1)  # 全为True时,返回True,否则返回False

False

In [87]:
# & 运算(and)
np.sum((x > 3) & (x < 8))  
# 统计x>3且小于8的数量,注意是'&',而不是'and'
# 因为x>3或x<8返回的都是多个元素,多个元素一一比较,可以理解为是位运算.
# 单个元素比较使用'and' 

4

In [90]:
(5 > 3) and (2 > 1)

True

In [96]:
# | 运算(or)
np.sum((x < 5) | (x > 1))  # 判断最后一个为True的条件,参与计算

16

In [98]:
# ~ 运算(非)
np.sum(~(x == 1))  # 统计不等于1的数量

15

In [100]:
# 矩阵同样适用上述函数操作
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
np.sum(X < 5)  

4

In [105]:
np.sum(X % 2 ==0)  # 统计有多少个偶数

8

In [107]:
np.sum(X % 2 ==0, axis=1)  # 沿列的方向(即行)统计

array([2, 2, 2, 2])

In [109]:
np.sum(X % 2 ==0, axis=0)

array([0, 4, 0, 4])

In [111]:
np.any(X < 5)

True

In [113]:
np.all(X > 5)

False

In [116]:
np.any(X > 5,axis=1)

array([False,  True,  True,  True])

In [118]:
np.any(X > 5,axis=0)

array([ True,  True,  True,  True])

In [121]:
np.all(X > 2, axis=0)

array([False, False,  True,  True])

In [122]:
X[X[:, 3] %3 == 0,:]  # 返回 '最后一列元素能被3整除的' 行

array([[ 9, 10, 11, 12]])